//-------------------------------------------------
// sinrom_tb
// This file was auto-generated by nromgen 2015-11-02T04:13:19
//-------------------------------------------------
module sinrom_tb ();
	reg CLK;
	reg RESET_X;
	reg [8:0] ADR;
	wire [23:0] DATA;
	integer i;

	parameter PERIOD = 10.0;
	always # (PERIOD/2) CLK = ~CLK;
	initial begin CLK = 1;end

	sinrom U0 (
		.CLK(CLK),
		.RESET_X(RESET_X),
		.ADR(ADR),
		.DATA(DATA)
	);

	initial begin
		i=$fopen("dump.txt");
		#1 RESET_X = 1; ADR = 0;
		# (PERIOD * 3)  RESET_X = 0;
		# (PERIOD * 5)  RESET_X = 1;
		for(i=0;i<512;i=i+1)begin
			ADR = i;
			# (PERIOD) $fwrite(i, "%X\n", DATA);
		end
		# (PERIOD)  $finish();
	end
endmodule
