//-------------------------------------------------
// sinrom_template
// This file was auto-generated by nromgen 2015-11-02T04:13:19
//-------------------------------------------------

	sinrom sinrom (
		.CLK(),
		.RESET_X(),
		.ADR(),
		.DATA()
	);
