//-------------------------------------------------
// sinrom_template
// This file was auto-generated by nromgen 2015-11-09T15:26:57
//-------------------------------------------------

	sinrom sinrom (
		.CLK(),
		.RESET_X(),
		.ADR(),
		.DATA()
	);
